---
title: "Predicting Home Prices Using Advanced Regression Techniques"
author: "Zihan Ye, Sohum Patnaik"
date: "3/2/2018"
output:
  word_document: default
  pdf_document: default
---
## Setting Up
```{r,warning=FALSE,message=FALSE,results='hide'}
## load required packages
library(mgcv)
library(ggplot2)
library(reshape2)
library(plyr)
library(rpart)
library(rpart.plot)
library(randomForest)
library(neuralnet)
library(caret)
library(AppliedPredictiveModeling)

## load the dataset
rawData <-read.csv("./Data/train.csv")
```

## Data Cleaning
```{r}
## initialize new dataframe
ProcessedData <- rawData

## specify levels for categorical variables and reassign NA's to "None"
levels(ProcessedData$Alley) <- c("Grvl", "Pave", "None")
ProcessedData$Alley[which(is.na(ProcessedData$Alley))] <- "None"

levels(ProcessedData$BsmtCond) <- c("Fa", "Gd", "Po", "TA", "None")
ProcessedData$BsmtCond[which(is.na(ProcessedData$BsmtCond))] <- "None"

levels(ProcessedData$BsmtExposure) <- c("Av", "Gd", "Mn", "No", "None")
ProcessedData$BsmtExposure[which(is.na(ProcessedData$BsmtExposure))] <- "None"

levels(ProcessedData$BsmtFinType1) <- c("ALQ", "BLQ", "GLQ", "LwQ", "Rec", "Unf", "None")
ProcessedData$BsmtFinType1[which(is.na(ProcessedData$BsmtFinType1))] <- "None"

levels(ProcessedData$BsmtFinType2) <- c("ALQ", "BLQ", "GLQ", "LwQ", "Rec", "Unf", "None")
ProcessedData$BsmtFinType2[which(is.na(ProcessedData$BsmtFinType2))] <- "None"

## This variable already has a level called "None", so we can't assume that's what NA's mean. 
ProcessedData <- ProcessedData[-which(is.na(ProcessedData$MasVnrType)), ]        # only 8 NA's, so we'll drop them
summary(ProcessedData$MasVnrArea)

# NA means no basement for this variable
levels(ProcessedData$BsmtQual) <- c("Ex", "Fa", "Gd", "TA", "None")
ProcessedData$BsmtQual[which(is.na(ProcessedData$BsmtQual))] <- "None"

# Electrical -- make it other
levels(ProcessedData$Electrical) <- c("FuseA", "FuseF", "FuseP", "Mix", "SBrkr", "Other")
ProcessedData$Electrical[which(is.na(ProcessedData$Electrical))] <- "Other"

# FireplaceQu -- NA means no fireplace
levels(ProcessedData$FireplaceQu) <- c("Ex", "Fa", "Gd", "Po", "TA", "None")
ProcessedData$FireplaceQu[which(is.na(ProcessedData$FireplaceQu))] <- "None"

# GarageType, GarageFinish, GarageQual, GarageCond -- NA means no garage
levels(ProcessedData$GarageType) <- c("2Types", "Attchd", "Basment", "BuiltIn", "CarPort", "Detchd", "None")
ProcessedData$GarageType[which(is.na(ProcessedData$GarageType))] <- "None"

levels(ProcessedData$GarageFinish) <- c("Fin", "RFn", "Unf", "None")
ProcessedData$GarageFinish[which(is.na(ProcessedData$GarageFinish))] <- "None"

levels(ProcessedData$GarageQual) <- c("Ex", "Fa", "Gd", "Po", "TA", "None")
ProcessedData$GarageQual[which(is.na(ProcessedData$GarageQual))] <- "None"

levels(ProcessedData$GarageCond) <- c("Ex", "Fa", "Gd", "Po", "TA", "None")
ProcessedData$GarageCond[which(is.na(ProcessedData$GarageCond))] <- "None"

levels(ProcessedData$PoolQC) <- c("Ex", "Fa", "Gd", "None")
ProcessedData$PoolQC[which(is.na(ProcessedData$PoolQC))] <- "None"

levels(ProcessedData$Fence) <- c("GdPrv", "GdWo", "MnPrv", "MnWw", "None")
ProcessedData$Fence[which(is.na(ProcessedData$Fence))] <- "None"

levels(ProcessedData$MiscFeature) <- c("Gar2", "Othr", "Shed", "TenC", "None")
ProcessedData$MiscFeature[which(is.na(ProcessedData$MiscFeature))] <- "None"

## impute missing values with the mean
ProcessedData$GarageYrBlt[which(is.na(ProcessedData$GarageYrBlt))] <- round(mean(ProcessedData$GarageYrBlt, na.rm=TRUE))

# Lot Frontage -- NA means no lot, so Lot Frontage is 0
ProcessedData$LotFrontage[which(is.na(ProcessedData$LotFrontage))] <- 0

# rename for simplicity
house <- ProcessedData
```

## Exploratory Data Analysis
```{r}
# separate the quantitative and categorical variables
numeric<-sapply(house,is.numeric)
house.numeric <- house[,numeric]
house.categorical <- cbind(house[,!numeric], SalePrice=house$SalePrice)
qplot(x=Var1, y=Var2, data=melt(cor(house.numeric)),fill=value,geom="tile")

## create heatmap
vars<-c("GarageArea", "GarageCars", "Fireplaces", "TotRmsAbvGrd", "FullBath", "GrLivArea","X1stFlrSF","TotalBsmtSF","YearRemodAdd","YearBuilt","OverallQual")
selectvars <- house[vars]
qplot(x=Var1, y=Var2, data=melt(cor(selectvars)), fill=value, geom="tile")
```

```{r,echo=FALSE, results="hide",warning=FALSE,message=FALSE,error=FALSE, fig.keep='none'}
## define a function that plots the relationship between response and a number of explanatory variables

plotExplore <- function(formula,data){
  
    xvars <- attr(terms(formula,data=data),'term.labels')
    yvar <- all.vars(formula)[1]
    y <- data[,yvar]
    xclasses <- sapply(xvars,function(x)class(data[,x]))
    xuniqueval <- apply(data[,xvars],2,function(x) length(unique(x)))
    xvars1 <- xvars[xclasses %in% c('numeric','integer') & xuniqueval > 3]
    xvars2 <- xvars[xclasses %in% c('factor') | xuniqueval <= 3]

    par(mfrow=c(ceiling(length(xvars)/3),3))
    lapply(xvars1,function(x) X =   scatter.smooth(data[,x],y,
    xlab=x,ylab=yvar,col='grey',lwd=2,pch=20,span = .7))
    lapply(xvars2,function(x) boxplot(y~data[,x],xlab=x,ylab=yvar))
    return()
    
}
```

```{r,warning=FALSE}
## explore the relationship between sale price and various features in dataset
final<-c("GarageArea", "Fireplaces", "FullBath", "GrLivArea","X1stFlrSF","YearRemodAdd","YearBuilt","OverallQual")
plotExplore(SalePrice ~ GarageArea+Fireplaces+FullBath+GrLivArea+X1stFlrSF+YearRemodAdd+YearBuilt+OverallQual, data=house)
```

```{r}
plotExplore(SalePrice ~.,data=cbind(house.categorical[,1:9], SalePrice=house$SalePrice))
plotExplore(SalePrice ~.,data=cbind(house.categorical[,10:18], SalePrice=house$SalePrice))
plotExplore(SalePrice ~.,data=cbind(house.categorical[,19:27], SalePrice=house$SalePrice))
plotExplore(SalePrice ~.,data=cbind(house.categorical[,28:36], SalePrice=house$SalePrice))
plotExplore(SalePrice ~.,data=house.categorical[,37:44])
```


```{r}
## explore relationship between sale price and neighborhood
boxplot(SalePrice~Neighborhood, data=house, las=2)
NeighborhoodMean <- tapply(house$SalePrice, house$Neighborhood, mean)
summary(NeighborhoodMean)
```


## Data Pre-processing
```{r}
## split neighborhoods into four groups based on average sale price
NeighbLow <- names(which(NeighborhoodMean <= 136800))
NeighbMidLow <- names(which(NeighborhoodMean > 136800 & NeighborhoodMean <= 186600))
NeighbMidHigh <- names(which(NeighborhoodMean > 186600 & NeighborhoodMean <= 212600))
NeighbHigh <- names(which(NeighborhoodMean > 212600))

house$NH <- rep(NA,nrow(house))

## create new feature "NH" that tells us whether the average price is low, midlow, midhigh, or high
for(i in 1:dim(house)[1]){
  if(house[i,"Neighborhood"]%in%NeighbLow){
    house[i,"NH"]<-"Low"
  } else if(house[i,"Neighborhood"]%in%NeighbMidLow){
    house[i,"NH"]<-"MidLow"
  } else if(house[i,"Neighborhood"]%in%NeighbMidHigh){
    house[i,"NH"]<-"MidHigh"
  } else if(house[i,"Neighborhood"]%in%NeighbHigh){
    house[i,"NH"]<-"High"
  }
}

## convert "NH" feature into a factor
house$NH <- factor(house$NH)
```

```{r}
## create new feature called "saletype" that represents the type of sale (ex. Contract Low Interest)

house$ST <- rep(NA,nrow(house))
SaleLow<- c("COD","ConLD","ConLI","ConLw", "Oth")
SaleHigh <- c("New", "CWD", "WD", "Con")

for(i in 1:dim(house)[1]){
  
  if(house[i,"SaleType"]%in%SaleLow){
    house[i,"ST"]<-"Low"
  } else if(house[i,"SaleType"]%in%SaleHigh){
    house[i,"ST"]<-"High"
  }
  
}

house$ST <- factor(house$ST)
```

```{r}
exterior <- data.frame(house$Id, house$Exterior1st, house$Exterior2nd)
notSameIndex <- which(as.character(exterior[,2])!=as.character(exterior[,3]))
sameIndex <- which(as.character(exterior[,2])==as.character(exterior[,3]))

# 1245 of 1460 have same material
mean(house$SalePrice[notSameIndex])
mean(house$SalePrice[sameIndex])
```

```{r}
## split up dataset based on "exterior1st" and sale price, into four groups
ExtMean <- tapply(house$SalePrice, house$Exterior1st, mean)
quantile(ExtMean,seq(0,1,.333333))
ExtLow <- names(which(ExtMean <= 149701))
ExtMid <- names(which(ExtMean > 149701 & ExtMean <= 182152))
ExtHigh <- names(which(ExtMean > 182152))

house$Ext1st <- rep(NA,nrow(house))

for(i in 1:dim(house)[1]){
  if(house[i,"Exterior1st"]%in%ExtLow){
    house[i,"Ext1st"]<-"Low"
  } else if(house[i,"Exterior1st"]%in%ExtMid){
    house[i,"Ext1st"]<-"Mid"
  } else if(house[i,"Exterior1st"]%in%ExtHigh){
    house[i,"Ext1st"]<-"High"
  }
}
house$Ext1st <- factor(house$Ext1st)
```

```{r}
## specify levels for categorical variables

house$bsmt <- house$BsmtQual
levels(house$bsmt) <- c("Ex", "Fa", "Gd", "TA", "No")
house$bsmt[which(is.na(house$bsmt))] <- "No"
levels(house$bsmt)<-c("Ex", "FairNo", "Gd", "TA", "FairNo")
summary(house$bsmt)

house$extQu <- house$ExterQual
levels(house$extQu) <- c("Good", "Average", "Good", "Average")
summary(house$extQu)

house$kitQu <- house$KitchenQual
levels(house$kitQu) <- c("Good", "Average", "Good", "Average")
summary(house$kitQu)


```

```{r}
## remove redundant categorical variables for which we created simplified versions above 

house2<-house
remove<-c("KitchenQual","ExterQual","BsmtQual","Exterior1st","Neighborhood","SaleType")
house2<-house2[,!(names(house2) %in% remove)]
```

## Model Fitting

### GAM
```{r}
set.seed(100)
finalGAM <- train(SalePrice ~ GarageArea+Fireplaces+TotRmsAbvGrd+FullBath+GrLivArea+X1stFlrSF+TotalBsmtSF+YearRemodAdd+YearBuilt+OverallQual+NH+ST+Ext1st+bsmt+extQu+kitQu, data=house2, method = 'gam', trControl = trainControl("cv",5)) 
finalGAM
summary(finalGAM)
```

### Regression Tree
```{r}
regTree <- train(SalePrice ~ ., data = house2, method = 'rpart1SE', trControl = trainControl("cv",5))
regTree
summary(regTree)
```

### Random forest

```{r}
rForest <- train(SalePrice~., data = house2, method = 'rf', trControl = trainControl("cv",5))
rForest
summary(rForest)
```

### Neural Network
```{r}
inclNnet<- c("GarageArea", "Fireplaces", "FullBath", "GrLivArea", "X1stFlrSF",
             "YearRemodAdd", "YearBuilt", "OverallQual", "NH", "SaleType",
             "GarageCars", "ExterQual", "TotalBsmtSF", "SalePrice")

NNData <- data.frame(lapply(house2[, names(house2) %in% inclNnet], as.numeric))

nnetGrid <- expand.grid(decay = c(0, .001, 0.01, .1), size = c(3,3))
set.seed(0)
nnetModel <- caret::train(SalePrice ~ ., data = NNData, method = 'nnet', 
                          tuneGrid = nnetGrid, trControl = trainControl("cv",5), 
                          preProc = c('center','scale'), linout = TRUE, trace = FALSE,
                          MaxNWts = 5 * (ncol(NNData) + 1) + 5 + 1, maxit = 100)
```


## Pre-processing the Test Data (Same as Training Data)
```{r}
test<-read.csv("./Data/test.csv")
ProcessedData <- test

## Make same changes we did to training data
levels(ProcessedData$Alley) <- c("Grvl", "Pave", "None")
ProcessedData$Alley[which(is.na(ProcessedData$Alley))] <- "None"

levels(ProcessedData$BsmtQual) <- c("Ex", "Fa", "Gd", "TA", "None")
ProcessedData$BsmtQual[which(is.na(ProcessedData$BsmtQual))] <- "None"

levels(ProcessedData$BsmtCond) <- c("Fa", "Gd", "Po", "TA", "None")
ProcessedData$BsmtCond[which(is.na(ProcessedData$BsmtCond))] <- "None"

levels(ProcessedData$BsmtExposure) <- c("Av", "Gd", "Mn", "No", "None")
ProcessedData$BsmtExposure[which(is.na(ProcessedData$BsmtExposure))] <- "None"

levels(ProcessedData$BsmtFinType1) <- c("ALQ", "BLQ", "GLQ", "LwQ", "Rec", "Unf", "None")
ProcessedData$BsmtFinType1[which(is.na(ProcessedData$BsmtFinType1))] <- "None"

levels(ProcessedData$BsmtFinType2) <- c("ALQ", "BLQ", "GLQ", "LwQ", "Rec", "Unf", "None")
ProcessedData$BsmtFinType2[which(is.na(ProcessedData$BsmtFinType2))] <- "None"

levels(ProcessedData$Electrical) <- c("FuseA", "FuseF", "FuseP", "Mix", "SBrkr", "Other")
ProcessedData$Electrical[which(is.na(ProcessedData$Electrical))] <- "Other"

levels(ProcessedData$FireplaceQu) <- c("Ex", "Fa", "Gd", "Po", "TA", "None")
ProcessedData$FireplaceQu[which(is.na(ProcessedData$FireplaceQu))] <- "None"

levels(ProcessedData$GarageType) <- c("2Types", "Attchd", "Basment", "BuiltIn", "CarPort", "Detchd", "None")
ProcessedData$GarageType[which(is.na(ProcessedData$GarageType))] <- "None"

levels(ProcessedData$GarageFinish) <- c("Fin", "RFn", "Unf", "None")
ProcessedData$GarageFinish[which(is.na(ProcessedData$GarageFinish))] <- "None"

levels(ProcessedData$GarageQual) <- c("Ex", "Fa", "Gd", "Po", "TA", "None")
ProcessedData$GarageQual[which(is.na(ProcessedData$GarageQual))] <- "None"

levels(ProcessedData$GarageCond) <- c("Ex", "Fa", "Gd", "Po", "TA", "None")
ProcessedData$GarageCond[which(is.na(ProcessedData$GarageCond))] <- "None"


ProcessedData$GarageYrBlt[which(is.na(ProcessedData$GarageYrBlt))] <- round(mean(ProcessedData$GarageYrBlt, na.rm=TRUE))

levels(ProcessedData$PoolQC) <- c("Ex", "Fa", "Gd", "None")
ProcessedData$PoolQC[which(is.na(ProcessedData$PoolQC))] <- "None"

levels(ProcessedData$Fence) <- c("GdPrv", "GdWo", "MnPrv", "MnWw", "None")
ProcessedData$Fence[which(is.na(ProcessedData$Fence))] <- "None"

levels(ProcessedData$MiscFeature) <- c("Gar2", "Othr", "Shed", "TenC", "None")
ProcessedData$MiscFeature[which(is.na(ProcessedData$MiscFeature))] <- "None"

summary(ProcessedData[which(is.na(ProcessedData$LotFrontage)),]$LotConfig)
ProcessedData$LotFrontage[which(is.na(ProcessedData$LotFrontage))] <- 0

ProcessedData$MSZoning[which(is.na(ProcessedData$MSZoning))] <- as.factor("RL")

ProcessedData$Utilities[which(is.na(ProcessedData$Utilities))] <- as.factor("AllPub")

ProcessedData$Exterior1st[which(is.na(ProcessedData$Exterior1st))] <- as.factor("VinylSd")

ProcessedData$Exterior2nd[which(is.na(ProcessedData$Exterior2nd))] <- as.factor("VinylSd")

ProcessedData$MasVnrType[which(is.na(ProcessedData$MasVnrType))] <- as.factor("None")

ProcessedData$MasVnrArea[which(is.na(ProcessedData$MasVnrArea))] <- 0

ProcessedData$BsmtFinSF1[which(is.na(ProcessedData$BsmtFinSF1))] <- 0

ProcessedData$BsmtFinSF2[which(is.na(ProcessedData$BsmtFinSF2))] <- 0

ProcessedData$BsmtUnfSF[which(is.na(ProcessedData$BsmtUnfSF))] <- 0

ProcessedData$TotalBsmtSF[which(is.na(ProcessedData$TotalBsmtSF))] <- 0

ProcessedData$BsmtFullBath[which(is.na(ProcessedData$BsmtFullBath))] <- 0

ProcessedData$BsmtHalfBath[which(is.na(ProcessedData$BsmtHalfBath))] <- 0

ProcessedData$KitchenQual[which(is.na(ProcessedData$KitchenQual))] <- as.factor("TA")

ProcessedData$Functional[which(is.na(ProcessedData$Functional))] <- as.factor("Typ")

ProcessedData$GarageCars[which(is.na(ProcessedData$GarageCars))] <- 0

ProcessedData$GarageArea[which(is.na(ProcessedData$GarageArea))] <- 0

ProcessedData$SaleType[which(is.na(ProcessedData$SaleType))] <- as.factor("WD")

houseTest <- ProcessedData
```

```{r}
houseTest$NH <- rep(NA,nrow(houseTest))

for(i in 1:dim(houseTest)[1]){
  if(houseTest[i,"Neighborhood"]%in%NeighbLow){
    houseTest[i,"NH"]<-"Low"
  } else if(houseTest[i,"Neighborhood"]%in%NeighbMidLow){
    houseTest[i,"NH"]<-"MidLow"
  } else if(houseTest[i,"Neighborhood"]%in%NeighbMidHigh){
    houseTest[i,"NH"]<-"MidHigh"
  } else if(houseTest[i,"Neighborhood"]%in%NeighbHigh){
    houseTest[i,"NH"]<-"High"
  }
}

houseTest$NH <- factor(houseTest$NH)
```

```{r}
houseTest$ST <- rep(NA,nrow(houseTest))

for(i in 1:dim(houseTest)[1]){
  
  if(houseTest[i,"SaleType"]%in%SaleLow){
    houseTest[i,"ST"]<-"Low"
  } else if(houseTest[i,"SaleType"]%in%SaleHigh){
    houseTest[i,"ST"]<-"High"
  }
  
}

houseTest$ST <- factor(houseTest$ST)
```

```{r}
houseTest$Ext1st <- rep(NA,nrow(houseTest))

for(i in 1:dim(houseTest)[1]){
  
  if(houseTest[i,"Exterior1st"]%in%ExtLow){
    houseTest[i,"Ext1st"]<-"Low"
  } else if(houseTest[i,"Exterior1st"]%in%ExtMid){
    houseTest[i,"Ext1st"]<-"Mid"
  } else if(houseTest[i,"Exterior1st"]%in%ExtHigh){
    houseTest[i,"Ext1st"]<-"High"
  }
  
}
houseTest$Ext1st <- factor(houseTest$Ext1st)
```

```{r}
## specify levels for categorical variables

houseTest$bsmt <- houseTest$BsmtQual
levels(houseTest$bsmt) <- c("Ex", "Fa", "Gd", "TA", "No")
houseTest$bsmt[which(is.na(houseTest$bsmt))] <- "No"
levels(houseTest$bsmt)<-c("Ex", "FairNo", "Gd", "TA", "FairNo")
summary(houseTest$bsmt)

houseTest$extQu <- houseTest$ExterQual
levels(houseTest$extQu) <- c("Good", "Average", "Good", "Average")
summary(houseTest$extQu)

houseTest$kitQu <- houseTest$KitchenQual
levels(houseTest$kitQu) <- c("Good", "Average", "Good", "Average")
summary(houseTest$kitQu)
```


```{r}
## remove redundant categorical variables for which we created simplified versions above 
houseTest2<-houseTest
remove<-c("KitchenQual","ExterQual","BsmtQual","Exterior1st","Neighborhood","SaleType")
houseTest2<-houseTest2[,!(names(houseTest2) %in% remove)]
```

## Exporting Predictions
```{r}
gamdata<-houseTest2[!complete.cases(houseTest2),]
forestdata<-houseTest2[complete.cases(houseTest2),]
gamindex<- gamdata$Id
forestindex<-forestdata$Id


forestPreds<-data.frame(predict(rForest,forestdata))
gamPreds<-data.frame(predict(finalGAM,newdata=gamdata))


forestPreds<-cbind.data.frame(forestindex,forestPreds)
gamPreds<-cbind.data.frame(gamindex,gamPreds)
final<-rbind.data.frame(forestPreds, gamPreds)
names(final) <- c("Id", "SalePrice")
submission <- final[order(final$Id),] 
write.csv(submission,file="submission.csv", row.names=FALSE)
```


